# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buddy', to='login_register.User')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='planner', to='login_register.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companion',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip', to='travels.Trip'),
        ),
    ]
