# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20160923_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='buddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Companion', to='login_register.User'),
        ),
        migrations.AlterField(
            model_name='companion',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Companion', to='travels.Trip'),
        ),
    ]
